Update telemetry dependency to stable ~> 1.0
absinthe-graphql/dataloader pull request #132
Opened 2021-08-24 13:16 UTC by bmuller

There [were not changes in the Telemetry 1.0.0 release](https://github.com/beam-telemetry/telemetry/blob/main/CHANGELOG.md#100) - but it does represent the first "stable" version of the API.

2021-08-24 17:37 UTC, benwilson512 requested changes
Let's make this an `or` so that it maintains compatibility.

2021-08-24 17:37 UTC, benwilson512 commented on mix.exs
> +      {:telemetry, "~> 1.0"},
```suggestion
      {:telemetry, "~> 1.0 or ~> 0.4"},
```

2021-08-24 17:38 UTC, merged

2021-09-27 20:33 UTC, edennis commented
Any chance at a version bump to include this?

2021-10-03 11:04 UTC, krainboltgreene commented
Jumping in here because phoenix 1.6 released with telemetry 1.0.