Safely add distinct on preload_lateral
absinthe-graphql/dataloader pull request #143
Opened 2022-04-19 16:28 UTC by cspeper

Only add a distinct to a query if it does not already have one to avoid:
```
%Ecto.Query.CompileError{message: "only one distinct expression is allowed in query"
```

2022-05-16 11:24 UTC, peaceful-james commented on lib/dataloader/ecto.ex
> +        %Ecto.Query{distinct: dist} = query
Would this be cleaner if it was pattern-matched in the function arguments?
For example
```
defp maybe_distinct(%Ecto.Query{distinct: dist} = query, _) when dist, do: query
```
Then the rest of the patterns can assume `dist` is false or nil.
```
defp maybe_distinct(query, [%Ecto.Association.Has{}, %Ecto.Association.BelongsTo{} | _]), do: distinct(query, true)

defp maybe_distinct(query, [%Ecto.Association.ManyToMany{} | _]), do: distinct(query, true)
```

2022-05-16 13:11 UTC, benwilson512 requested changes
Thanks for the PR! A small change to the test and we can get this merged in.

2022-05-16 13:11 UTC, benwilson512 commented on test/dataloader/ecto/limit_query_test.exs
> +    |> distinct(true)
Can we make a dedicated clause for this? With this change every clause is distinct, which would make test cases showing that we _add_ a distinct no longer valid.

2022-06-30 10:14 UTC, cspeper commented
@benwilson512 @peaceful-james Sorry for the delay and thanks for the feedback!  I think I addressed both comments.

2022-06-30 14:50 UTC, benwilson512 approved these changes
Great, thank you!

2022-06-30 14:59 UTC, benwilson512 commented
@cspeper can you run `mix format` on the code base so that the CI passes?

2022-06-30 21:14 UTC, cspeper commented
@benwilson512 Looks like the format issue was on master but I went ahead and ran the update.  I'll merge once it's approved and passes CI.  Thanks!

2022-07-01 15:02 UTC, benwilson512 commented
Ahhh haha `then` isn't supported on older Elixirs. I'll make a tweak to replace it with a regular function.

2022-07-11 12:48 UTC, cspeper commented
> Ahhh haha `then` isn't supported on older Elixirs. I'll make a tweak to replace it with a regular function.



> Ahhh haha `then` isn't supported on older Elixirs. I'll make a tweak to replace it with a regular function.

Hi @benwilson512 Is there anything more you needed me to do with this PR?  It looks like master has the same failure

2022-07-11 21:18 UTC, benwilson512 commented
Ah good point, oK we're good to go then, thanks!

2022-07-11 21:18 UTC, merged